# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: "daily"

  # Set update schedule for Maven - disabled so that JUnit vulnerability takes precidence in demos
  # - package-ecosystem: "maven"
  #   directory: "/"
  #   schedule:
  #     # Check for updates to GitHub Actions every week
  #     interval: "weekly"

  # Set update schedule for Terraform
  - package-ecosystem: "terraform"
    directory: "/.demo/terraform"
    schedule:
      # Check for updates to Terraform every month
      interval: "monthly"
